# Generated by Django 5.2.7 on 2025-11-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_shippingzone_order_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingzone',
            name='per_kg_rate',
        ),
    ]
